[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "milwaukee-restaurant-parser"
version = "0.1.5"
dependencies = [
    "beautifulsoup4>=4.6.1",
    "aiohttp>=3.14.3",
    "python-dateutil>=2.9.0",
]
authors = [
    { name="Jason Fry", email="your.email@example.com" },
]
description = "Gets Milwaukee restaurant grades"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.setuptools.packages.find]
where = ["."]